# Generated by Django 4.2 on 2023-07-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_y_apellido', models.CharField(max_length=30, unique=True)),
                ('zona', models.CharField(choices=[('San Martin', 'San Martin'), ('Italia', 'Italia'), ('Belgrano', 'Belgrano'), ('Paso', 'Paso'), ('Rocha', 'Rocha')], max_length=10)),
                ('tipo', models.CharField(choices=[('P', 'Paseador'), ('C', 'Cuidador')], max_length=1)),
                ('habilitado', models.BooleanField()),
                ('fecha_fin_deshabilitacion', models.DateField(verbose_name='Deshabilitar hasta')),
            ],
        ),
    ]
