# Generated by Django 4.2 on 2023-07-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
