# Generated by Django 4.2 on 2023-07-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listados', '0002_alter_trabajador_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_fin_deshabilitacion',
            field=models.DateField(blank=True, null=True, verbose_name='Deshabilitar hasta'),
        ),
    ]
