# Generated by Django 4.2 on 2023-07-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listados', '0003_alter_trabajador_fecha_fin_deshabilitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(default='alive.soluciones.software@gmail.com', max_length=254),
        ),
    ]
