# Generated by Django 4.2 on 2023-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listados', '0004_trabajador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
