# Generated by Django 4.2 on 2023-06-04 18:03

from django.db import migrations, models
import usuarios_y_perros.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_y_perros', '0002_perro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios_y_perros.models.generate_unique_filename),
        ),
    ]
