# Generated by Django 4.2 on 2023-06-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_y_perros', '0003_alter_perro_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descuento_atencion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Descuento'),
        ),
    ]
