# Generated by Django 4.2 on 2023-06-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_y_perros', '0004_usuario_descuento_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(choices=[('MEST', 'Mestizo'), ('LABR', 'Labrador'), ('BULL', 'Bulldog'), ('BEAG', 'Beagle'), ('BOXE', 'Boxer'), ('GOLD', 'Golden')], max_length=4),
        ),
    ]
