# Generated by Django 4.2 on 2023-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_remove_publicacion_fechanac_remove_publicacion_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
