# Generated by Django 4.2 on 2023-05-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_alter_publicacion_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='raza',
            field=models.CharField(blank=True, choices=[('MEST', 'Mestizo'), ('LABR', 'Labrador'), ('BULL', 'Bulldog'), ('BEAG', 'Beagle'), ('BOXE', 'Boxer')], max_length=4),
        ),
    ]
