# Generated by Django 4.2 on 2023-06-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_publicacion_raza'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaniaDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre de la campaña')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite para donar')),
                ('monto_recaudado', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True, verbose_name='Monto recaudado hasta el momento')),
            ],
        ),
    ]
