# Generated by Django 4.2 on 2023-06-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_publicacion_raza'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaniaDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de la campaña')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('fecha_limite', models.DateField(verbose_name='Fecha límite para donar')),
                ('monto_recaudado', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Monto recaudado hasta el momento')),
            ],
        ),
    ]
