# Generated by Django 4.2 on 2023-06-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_campaniadonacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaniadonacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='campaniadonacion',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite para donar'),
        ),
        migrations.AlterField(
            model_name='campaniadonacion',
            name='monto_recaudado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, null=True, verbose_name='Monto recaudado hasta el momento'),
        ),
    ]
