# Generated by Django 4.2 on 2023-06-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_tarjeta_donacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='clave',
            field=models.CharField(max_length=15, verbose_name='Clave de la tarjeta de crédito'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(verbose_name='Fecha de vencimiento de la tarjeta de crédito'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.IntegerField(verbose_name='Número de la tarjeta de crédito'),
        ),
    ]
