# Generated by Django 4.2 on 2023-06-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_alter_tarjeta_clave_alter_tarjeta_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='clave',
            field=models.CharField(max_length=15, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
