# Generated by Django 4.2 on 2023-07-02 18:00

from django.db import migrations, models
import usuarios_y_perros.models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0010_perdidoencontrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios_y_perros.models.generate_unique_filename),
        ),
    ]
