# Generated by Django 4.2 on 2023-07-08 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0012_alter_perdidoencontrado_edadaproximada'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
