# Generated by Django 4.2 on 2023-07-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios_y_perros', '0005_alter_perro_raza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_tinder', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=4)),
                ('perro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios_y_perros.perro')),
            ],
        ),
    ]
