# Generated by Django 4.2 on 2023-05-18 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios_y_perros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateField()),
                ('sugerencia_turno', models.CharField(max_length=50)),
                ('estado_turno', models.CharField(choices=[('SOLI', 'Solicitado'), ('ACEP', 'Aceptado'), ('RECH', 'Rechazado'), ('CANC', 'Cancelado'), ('CONC', 'Concretado')], default='SOLI', max_length=4)),
                ('motivo', models.CharField(choices=[('VACA', 'Vacunación para enfermedades'), ('VACB', 'Vacunación antiirrábica'), ('DESP', 'Desparasitación'), ('CONS', 'Consulta general'), ('URGE', 'Urgencia')], default='CONS', max_length=4)),
                ('franja_horaria', models.CharField(choices=[('TM', 'Mañana'), ('TT', 'Tarde'), (None, 'Seleccione una opción')], max_length=2)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_y_perros.perro')),
            ],
        ),
    ]
