# Generated by Django 4.2 on 2023-06-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(choices=[('VACA', 'Vacunación para enfermedades'), ('VACB', 'Vacunación antirrábica'), ('DESP', 'Desparasitación'), ('CONS', 'Consulta general'), ('URGE', 'Urgencia')], default='CONS', max_length=4),
        ),
    ]
