# Generated by Django 4.2 on 2023-06-05 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_turnos', '0002_alter_turno_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observaciones', models.CharField(max_length=50)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema_de_turnos.turno')),
            ],
        ),
    ]
