# Generated by Django 4.2 on 2023-06-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_turnos', '0005_alter_turno_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
