# Generated by Django 4.2 on 2023-06-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_turnos', '0005_alter_turno_motivo_inyeccion'),
        ('sistema_de_turnos', '0006_alter_atencion_observaciones'),
    ]

    operations = [
    ]
