# Generated by Django 4.2 on 2023-06-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_de_turnos', '0008_atencion_descuento'),
        ('sistema_de_turnos', '0008_remove_inyeccion_cantidad_de_desparasitante_and_more'),
    ]

    operations = [
    ]
